### ISSUE TITLE
User can add a vehicle profile

### ISSUE THREAD

**Issue by wonseop-lee** [wonseop-lee/ajax-project#3]
## 💰 Motivation

The user needs to add a new vehicle profile.

## 📐 Plan

Display a separate page to add a new VIN number and photo.

## ✅ Task List

- [ ] Create a header that displays the page title.
- [ ] Create profile photo section.
- [ ] Create a form with two inputs for url of photo and VIN.
- [ ] Create a button for submit within the form.
- [ ] Create a button for cancel.
- [ ] Photo section should update with new URL.
- [ ] When submit button is pressed, the form should store the info and display the main page.
- [ ] When cancel button is pressed, the form values does not get stored and display the main page.
