### ISSUE TITLE
User can view a vehicle profile

### ISSUE THREAD

**Issue by wonseop-lee** [wonseop-lee/ajax-project#4]
## 💰 Motivation

The user needs to see individual profile.

## 📐 Plan

Display a separate profile page for selected profile.

## ✅ Task List

- [ ] Create a heading, showing make, model, and year.
- [ ] Parse the local storage.
- [ ] Profile section displays the correct photo.
- [ ] Create a list displaying details of the VIN as such: VIN, make, model, year, trim, displacement, and engine brake.
- [ ] Create two buttons for edit profile and back to main menu.
- [ ] Listen for edit profile.
- [ ] Listen for back to main menu button. Once pressed, main screen is displayed.
- [ ] Remove all CSS styling that had no affect or was otherwise unneccessary.
- [ ] Test all functionality again.
