### ISSUE TITLE
User can edit a vehicle profile

### ISSUE THREAD

**Issue by wonseop-lee** [wonseop-lee/ajax-project#5]
## 💰 Motivation

The user needs to update a profile.

## 📐 Plan

Display a separate page with edit functions.

## ✅ Task List

- [ ] Connect edit profile button on view profile page to display this page.
- [ ] Create an input for photo URL.
- [ ] Create an input for VIN.
- [ ] Create submit button.
- [ ] Listen for the submit button, when pressed, the data is updated and update the local storage, and display view profile page.
- [ ] Create cancel button.
- [ ] Listen for the cancel button, when pressed, the view profile page is displayed, and display view profile page.
- [ ] Create delete profile.
- [ ] Listen for the delete button.
