### ISSUE TITLE
User can remove a profile

### ISSUE THREAD

**Issue by wonseop-lee** [wonseop-lee/ajax-project#6]
## 💰 Motivation

The user needs to remove a profile.

## 📐 Plan

Create a delete profile page with delete functionality.

## ✅ Task List

- [ ] Display message if the user wants to delete the profile.
- [ ] Create yes button.
- [ ] Listen for 'click' event for yes button, when pressed, main screen is displayed.
- [ ] Remove the entry from the data.
- [ ] Create no button.
- [ ] Listen for 'click' event for no button, when pressed, edit profile page is displayed.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again.
